version: 1
labels:
  - label: "major"
    title: "/^(?i)(.*?(\bbreaking\b).*)$/"
  - label: "major"
    body: "/^(?i)(.*?(\bbreaking:\b).*)$/"
  - label: "minor"
    title: "/^(?i)(.*?(\bfeature\b).*)$/"
  - label: "minor"
    body: "/^(?i)(.*?(\bfeature:\b).*)$/"
  - label: "minor"
    title: "/^(?i)(.*?(\bfeat\b).*)$/"
  - label: "minor"
    body: "/^(?i)(.*?(\bfeat:\b).*)$/"
  - label: "patch"
    title: "/^(?i)(.*?(\bfix\b).*)$/"
  - label: "patch"
    body: "/^(?i)(.*?(\bfix:\b).*)$/"
  - label: "patch"
    title: "/^(?i)(.*?(\bchore\b).*)$/"
  - label: "patch"
    body: "/^(?i)(.*?(\bchore:\b).*)$/"