version: 1
labels:
  - label: "major"
    title: "^(?i)breaking.*"
  - label: "major"
    body: "^(?i)breaking.*"
  - label: "minor"
    title: "^(?i)feature.*"
  - label: "minor"
    body: "^(?i)feature.*"
  - label: "minor"
    title: "^(?i)feat.*"
  - label: "minor"
    body: "^(?i)feat.*"
  - label: "patch"
    title: "^(?i)fix.*"
  - label: "patch"
    body: "^(?i)fix.*"
  - label: "patch"
    title: "^(?i)chore.*"
  - label: "patch"
    body: "^(?i)chore.*"
  - label: "skip-changelog"
    title: "^(?i)doc.*"
  - label: "skip-changelog"
    body: "^(?i)doc.*"
  - label: "skip-changelog"
    title: "^(?i)skip-changelog.*"
  - label: "skip-changelog"
    body: "^(?i)skip-changelog.*"