version: 1
labels:
  - label: "major"
    title: "^(?i)breaking.*"
  - label: "major"
    body: "^(?i)breaking.*"
  - label: "minor"
    title: "^(?i)feature.*"
  - label: "minor"
    body: "^(?i)feature.*"
  - label: "minor"
    title: "^(?i)feat.*"
  - label: "minor"
    body: "^(?i)feat.*"
  - label: "patch"
    title: "^(?i)fix.*"
  - label: "patch"
    body: "^(?i)fix.*"
  - label: "chore"
    title: "^(?i)chore.*"
  - label: "chore"
    body: "^(?i)chore.*"
  - label: "doc"
    title: "^(?i)doc.*"
  - label: "doc"
    body: "^(?i)doc.*"