name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## What’s Changed

  $CHANGES

categories:
  - title: '🚀 Features'
    labels:
      - 'major'
      - 'minor'
  - title: '🐛 Bug Fixes'
    labels:
      - 'patch'
  - title: '🧰 Maintenance'
    label:
      - 'chore'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'

exclude-labels:
  - 'no-release'